In [1]:
import numpy as np

In [3]:
np.random.seed(42)

In [5]:
# Vector baru untuk kata "peace" dengan dimensi berbeda (7 dimensi dibandingkan 6 sebelumnya)
v_peace = np.array([0, 1, 0, 0, 1, 0, 0])  # "peace"
print("Vector 'peace':", v_peace)

Vector 'peace': [0 1 0 0 1 0 0]


In [7]:
# Matriks bobot baru dengan dimensi yang disesuaikan (7, 4) sebagai ilustrasi
weight = np.random.random_sample((7, 4))
print("Weight matrix:\n", weight)

Weight matrix:
 [[0.37454012 0.95071431 0.73199394 0.59865848]
 [0.15601864 0.15599452 0.05808361 0.86617615]
 [0.60111501 0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497 0.18340451]
 [0.30424224 0.52475643 0.43194502 0.29122914]
 [0.61185289 0.13949386 0.29214465 0.36636184]
 [0.45606998 0.78517596 0.19967378 0.51423444]]


In [9]:
# Perhitungan hidden layer untuk model Skip-Gram
hidden_layer_sg = np.dot(v_peace, weight)
print("Hidden layer (Skip-Gram):", hidden_layer_sg)

Hidden layer (Skip-Gram): [0.46026088 0.68075095 0.49002863 1.15740529]


In [11]:
# Matriks bobot baru untuk output layer
weight_prime = np.random.random_sample((4, 7))
print("Weight prime matrix:\n", weight_prime)

Weight prime matrix:
 [[0.59241457 0.04645041 0.60754485 0.17052412 0.06505159 0.94888554
  0.96563203]
 [0.80839735 0.30461377 0.09767211 0.68423303 0.44015249 0.12203823
  0.49517691]
 [0.03438852 0.9093204  0.25877998 0.66252228 0.31171108 0.52006802
  0.54671028]
 [0.18485446 0.96958463 0.77513282 0.93949894 0.89482735 0.59789998
  0.92187424]]


In [13]:
# Perhitungan output layer
o_love = np.dot(hidden_layer_sg, weight_prime)
print("Output layer result:", o_love)

Output layer result: [1.0537854  1.79654083 1.37007194 1.9563138  1.51800019 1.46667336
 2.11642061]
